---
- name: epdg
  hosts: epdg
  user: root
  vars_files:
    - "vars/network.yml"
  roles:
  - name: common
  - name: authorized_keys
  - name: network
    net_interface: enp7s0
    net_ips:
    - 10.74.0.11/24
    - 10.74.0.12/24
    - 10.74.0.13/24
    net_method: ifupdown

  - name: epdg
    net_method: ifupdown
    epdg_ipsec_traffic_fwmark: 2
    epdg_ipsec_traffic_rtable_name: epdg
    epdg_ipsec_traffic_rtable_number: 2
    epdg_tun_interface: gtp0
    epdg_ipsec_bind_ip: 213.95.46.81
    epdg_swx_hss_ip: 10.74.0.21
    epdg_gtpc_bind_ip: 10.74.0.12
    epdg_gtpc_pgw_ip: 10.74.0.23
    epdg_s6b_bind_ip: 10.74.0.12
    epdg_diameter_realm: "{{ diameter_realm }}"
