- name: host ims
  hosts: ims
  user: root
  vars_files:
    - "vars/network.yml"
  tasks:
    - name: configure hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
      - "10.74.0.21 hss.mnc042.mcc901.3gppnetwork.org"
      - "10.74.0.21 hss.mnc070.mcc901.3gppnetwork.org"
      - "10.74.0.21 hss.mnc042.mcc999.3gppnetwork.org"
      - "10.74.0.21 hss.mnc070.mcc999.3gppnetwork.org"
# TODO: add network configuration
  roles:
  - name: common
  - name: authorized_keys
  - name: network
    net_interface: enp7s0
    net_ips:
    - 10.74.0.31/24
    - 10.74.0.32/24
    - 10.74.0.33/24
    net_method: ifupdown

  - name: ims
    ims_mcc: "{{ mcc }}"
    ims_mnc: "{{ mnc }}"
    ims_pcscf_sip_bind: "udp:10.74.0.31:5060"
    ims_pcscf_diameter_bind_ip: 10.74.0.31
    ims_pcscf_diameter_bind_port: 3868

    ims_icscf_sip_bind: "udp:10.74.0.32:5060"
    ims_icscf_diameter_bind_ip: 10.74.0.32
    ims_icscf_diameter_bind_port: 3868

    ims_scscf_sip_bind: "udp:10.74.0.33:5060"
    ims_scscf_diameter_bind_ip: 10.74.0.33
    ims_scscf_diameter_bind_port: 3868
