---

# hss
- name: configure freediameter open5gs
  template:
    src: hss.conf
    dest: /etc/freeDiameter/hss.conf
  notify: restart open5gs-hssd

# pcrf
- name: configure pcrf
  template:
    src: pcrf.conf
    dest: /etc/freeDiameter/pcrf.conf
  notify: restart open5gs-pcrfd

# smf
- name: configure smf.yaml open5gs
  template:
    src: smf.yaml
    dest: /etc/open5gs/smf.yaml
  notify: restart open5gs-smfd

- name: configure smf diameter open5gs
  template:
    src: smf.conf
    dest: /etc/freeDiameter/smf.conf
  notify: restart open5gs-smfd

# upf
- name: configure upf open5gs
  template:
    src: upf.yaml
    dest: /etc/open5gs/upf.yaml
  notify: restart open5gs-upfd
